### ISSUE TITLE
Constraints on fourseven:scss to high for use with meteoric

### ISSUE THREAD

**Issue by ouya99** [rikonor/meteor-autoform-image-gallery#1]
While selecting package versions:
   error: Conflict: Constraint fourseven:scss@3.4.1 is not satisfied by fourseven:scss 3.2.0.
   Constraints on package "fourseven:scss":
- fourseven:scss@=3.2.0 <- top level
- fourseven:scss@3.2.0 <- meteoric:ionic-sass 0.3.0
- fourseven:scss@3.2.0 <- meteoric:ionicons-sass 0.1.7
- fourseven:scss@3.4.1 <- rikonor:autoform-image-gallery 0.0.1

Could you maybe adjust in a new version?

I did a manual update and download from github to solve it.

**Comment by rikonor** [comment]
Hey,

Is there a specific reason you need `fourseven:scss` at version `3.2.0`?
It looks like when you installed `fourseven:scss` you specified that version explicitly.

If you want to install the latest version you can `meteor remove fourseven:scss` then reinstall it without a version specifier. After that you shouldn't experience a problem.

There's no reason I can't downgrade the package requirements to `3.2.0` either, but seems to me that's not really necessary.

**Comment by ouya99** [comment]
Hi,

unfortunately after remove and add it will still be at

3.2.0*

Due to these constraints I mentioned in the issue.

Actually meteoric should upgrade.. sure its not your fault here.

**Comment by rikonor** [comment]
Both of the `meteoric` packages will upgrade automatically (since they require 3.2.0 or above).
The only hard requirement is when you installed 3.2.0 globally (I think you may have done `meteor add fourseven:scss@=3.2.0` at one point).

If you remove the hard requirement for 3.2.0 (just a matter of removing the package) and reinstall it with no version specifier - then all the packages should install fine.

Let me know if it's not working for you, I'll lower the version requirement on my end.

**Comment by ouya99** [comment]
=> Errors while initializing project:

While selecting package versions:
error: Conflict: Constraint fourseven:scss@3.4.1 is not satisfied by
fourseven:scss 3.2.0.
Constraints on package "fourseven:scss":
- fourseven:scss@=3.2.0 <- top level
- fourseven:scss@3.2.0 <- meteoric:ionic-sass 0.3.0
- fourseven:scss@3.2.0 <- meteoric:ionicons-sass 0.1.7
- fourseven:scss@3.4.1 <- rikonor:autoform-image-gallery 0.0.1

I do not recall setting it to 3.2.0 manually. Just as you said I did
remove and add fourseven:scss completely.

Also I could get past this by manipulating your files and lowering the
version you require to 3.2 manually. Just in case anybody has this
issue here.
Thanks for your offer and help anyway.

**Comment by rikonor** [comment]
Hey,

I lowered the version requirement to 3.2.
I was contemplating whether to leave out sass altogether since I could've just added a precompiled styling file, but for now I'll leave it.

Anyway, hope this takes care of this issue for you. Feel free to close or let me know if it's still not resolved.

**Comment by ouya99** [comment]
Thanks a lot.

Closing issue now
